import type { Metadata } from 'next'
import { cn } from '@/lib/utils'
import { fontMono } from '@/lib/fonts'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background text-text',
          fontMono.className,
        )}
      >
        {children}
      </body>
    </html>
  )
}
